### ISSUE TITLE
No clear description about how to delete a nested folder

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-cli#81]
Execute cmd `jcli job delete "rick folder" -b`. Then will got error output:

```
status code: 404
2019/07/27 09:24:41 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing //job/rick%20folder/doDelete. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

**Comment by cgrigel** [comment]
Dear @LinuxSuRen could you provide more info concerning this bug?
Since at the current moment, I can not reproduce this issue as: 
The nested folder can be deleted using the same endpoints as a REST API: `jcli job delete "hack-folder-01/job/hack-folder-02" -b` 
It looks like you trying to delete the nested folder without declaring the parent location.

**Comment by LinuxSuRen** [comment]
Hi @cgrigel ,thanks for providing the information. I can delete the nest folder follow your instructions. I think the problem which I met due to sperating whitespace instead of 'job'. Which means `jcli job delete "hack-folder-01 hack-folder-02" -b`.

I know that the REST API endpoint should be `/job/hack-folder-01/job/hack-folder-02`.

But it might not be a good way to pass the folder path. A user does not need to know the REST API path.

**Comment by cgrigel** [comment]
Dear @LinuxSuRen,
I think the end-user needs to know about the REST API path, and good point the following a unified style of a provide endpoints to identify the nesting level and inheritance for Jenkins objects.
Since the usage of whitespace instead of "/" a little bit confusing, and this more logical usage for the list of several jobs for deletion than for endpoints definition.

**Comment by LinuxSuRen** [comment]
Using whitespace might not be a good way. But I still think that the end-user does not need to know about the tech details about the REST API. I'd prefer using `hack-folder-01/hack-folder-02`. So people only need to know the folder or job name.
Of course, if the end-user gives a correct REST API which they might copy from the browser, it's best to support this situation.

**Comment by cgrigel** [comment]
Dear @LinuxSuRen,
You are right, incapsulate these things from the end-user may be a good point.
But, it will be required the additional logic and verification of the search endpoints by folder or job name.
Also, I think the issue label should be changed from bug to enhancement.

**Comment by LinuxSuRen** [comment]
@cgrigel Good advice!
